name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Install latest version of GCC on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update

          version=$(apt-cache pkgnames | sed -nr 's/^gcc-(([0-9]+\.?)+)$/\1/p' \
                             | sort -n | tail -n1)
          echo "The latest available GCC version: $version"

          sudo apt-get install gcc-$version g++-$version
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-$version 60 \
                                   --slave   /usr/bin/g++ g++ /usr/bin/g++-$version

      - name: Install libglfw3-dev & libglew-dev on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev
          sudo apt-get install -y libglew-dev

      - name: Install MinGW on Windows
        if: runner.os == 'Windows'
        run: choco install mingw --version 13.2.0 --x86_64 --no-progress

      - name: Add MinGW to PATH on Windows
        if: runner.os == 'Windows'
        run: echo "C:\Program Files\mingw-w64\bin" >> $GITHUB_PATH

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          ${{ matrix.os == 'windows-latest' && '-G "MinGW Makefiles"' || '' }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Zip build on macOS
        if: runner.os == 'macOS'
        run: |
          cd ${{ steps.strings.outputs.build-output-dir }}
          zip -r toast_macOS.zip toast.app
      - name: Upload zipped build on macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: toast_macOS
          path: ${{ steps.strings.outputs.build-output-dir }}/toast_macOS.zip
      
      - name: Zip build on Ubuntu
        if: runner.os == 'Linux'
        run: |
          cd ${{ steps.strings.outputs.build-output-dir }}
          zip -r toast_Linux.zip toast
      - name: Upload zipped build on Ubuntu
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: toast_Linux
          path: ${{ steps.strings.outputs.build-output-dir }}/toast_Linux.zip
      
      - name: Zip build on Windows
        if: runner.os == 'Windows'
        run: |
          cd ${{ steps.strings.outputs.build-output-dir }}
          Compress-Archive -Path toast.exe -DestinationPath toast_Windows.zip
      - name: Upload zipped build on Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: toast_Windows
          path: ${{ steps.strings.outputs.build-output-dir }}/toast_Windows.zip

