name: CMake on multiple platforms

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-14-large]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
          - os: ubuntu-22.04
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
          - os: macos-14-large # NOTE: start using macos-15-intel once this gets too old
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Check current GCC version
        if: runner.os == 'Linux'
        id: gcc_version
        shell: bash
        run: |
          version=$(g++ -dumpversion | cut -f1 -d.)
          echo "gcc_version=$version" >> $GITHUB_OUTPUT

      - name: Install latest version of GCC on Ubuntu if needed
        if: runner.os == 'Linux' && steps.gcc_version.outputs.gcc_version < 11
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update

          version=$(apt-cache pkgnames | sed -nr 's/^gcc-(([0-9]+\.?)+)$/\1/p' \
                             | sort -n | tail -n1)
          echo "The latest available GCC version: $version"

          sudo apt-get install gcc-$version g++-$version
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-$version 60 \
                                   --slave   /usr/bin/g++ g++ /usr/bin/g++-$version

      - name: Install libglfw3-dev & libglew-dev on Ubuntu
        if: runner.os == 'Linux'
        run: | # No need for sudo apt-get update, since we've done that on the previous step.
          sudo apt-get install -y libglfw3-dev
          sudo apt-get install -y libglew-dev

      - name: Install Ninja (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y ninja-build

        # It's probably pre-installed, but just in case ..
      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Install MinGW on Windows
        if: runner.os == 'Windows'
        run: choco install mingw --version 13.2.0 --x86_64 --no-progress

      - name: Add MinGW to PATH on Windows
        if: runner.os == 'Windows'
        run: echo "C:\Program Files\mingw-w64\bin" >> $GITHUB_PATH

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake (Ubuntu/macOS)
        if: runner.os != 'Windows'
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G Ninja
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G "MinGW Makefiles"
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build (Ubuntu/macOS)
        if: runner.os != 'Windows'
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} # We're using Ninja, no need for -j.

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -- -j $Env:NUMBER_OF_PROCESSORS

      # We need to do this to stop upload-artifact from uploading toast.app/Contents
      # instead of toast.app
      - name: (HACK) Move toast.app into macOS_build
        if: runner.os == 'macOS'
        run: |
          mkdir -p "${{ steps.strings.outputs.build-output-dir }}/macOS_build"
          mv "${{ steps.strings.outputs.build-output-dir }}/toast.app" "${{ steps.strings.outputs.build-output-dir }}/macOS_build/"

      - name: Upload build on macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: toast_macOS
          path: ${{ steps.strings.outputs.build-output-dir }}/macOS_build

      - name: Upload build on Ubuntu
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: toast_Linux
          path: ${{ steps.strings.outputs.build-output-dir }}/toast

      - name: Upload build on Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: toast_Windows
          path: ${{ steps.strings.outputs.build-output-dir }}/toast.exe
